DELETE FROM booking;
DELETE FROM showtime;
DELETE FROM movie;

ALTER SEQUENCE movie_id_seq RESTART WITH 1;

INSERT INTO movie (title, genre, duration, rating, release_year)
VALUES ('The Matrix', 'Sci-Fi', 136, 8.7, 1999);

-- assuming first autogenerated id will be 1
INSERT INTO showtime (movie_id, theater, start_time, end_time, price)
VALUES (1, 'Cinema 1', '2025-03-20 20:00:00', '2025-03-20 22:16:00', 12.50);
